import { SCENARIOS } from "./scenarios.js";
import { launchPageMarkup } from "./launch-page.js";
export function workspaceShell(W, H) {
  return `
<header class="topbar"><button class="brand" id="home-button" aria-label="DuckFly home"><img src="/duck.svg" alt=""><span class="brand-name">DuckFly</span></button><span class="platform" id="platform">Robot behavior studio</span><div class="top-actions"><button id="new-scene" class="primary" data-control disabled aria-haspopup="dialog"><span aria-hidden="true">＋</span> New scene</button><button id="share">Share scene</button><details class="app-menu"><summary>More</summary><div class="menu-content"><button id="show-launch">Welcome page</button><button id="room-button">Collaborate</button><button id="save">Save scene</button><button id="open">Open file</button><button id="about">About DuckFly</button></div></details></div></header>
<main id="home-page" class="home-page">
${launchPageMarkup()}
<div id="scene-catalog" hidden>
<div class="home-intro"><span class="eyebrow">DUCKFLY STUDIO</span><h1>Build a behavior. See it in motion.</h1><p>Choose a scene and connect signals to your duck’s actions. Watch the brain activity as you change the scene.</p><div class="home-meta"><span id="home-status" role="status">Loading the simulator…</span><button id="continue-scene" hidden>Return to scene</button></div></div>
<div class="section-heading"><div><h2 id="scene-catalog-title" tabindex="-1">Choose a scene</h2><p>Each scene opens in a setup wizard. Keep the defaults or adjust the connections.</p></div><span id="scenario-count">${SCENARIOS.length} scenes</span></div>
<div class="scenario-filters" role="group" aria-label="Filter scenes"><button data-scenario-filter="all" aria-pressed="true">All scenes</button><button data-scenario-filter="start" aria-pressed="false">Start here</button><button data-scenario-filter="vision" aria-pressed="false">Vision</button><button data-scenario-filter="brain" aria-pressed="false">Brain & body</button></div>
<div class="scenario-grid">${SCENARIOS.map((s, i) => `<button class="scenario-tile" data-scenario="${s.id}" data-control disabled><div class="scenario-image"><img src="/scenarios/${s.image??s.id}.${(s.image??s.id)==='kick'?'svg':'png'}" alt="${s.alt}"><span class="tile-tag">${s.tag}</span></div><div class="tile-copy"><span class="tile-number">SCENE ${String(i + 1).padStart(2, "0")}</span><h3>${s.title}</h3><p>${s.description}</p><span class="tile-launch">${s.action}<span aria-hidden="true">↗</span></span></div></button>`).join("")}</div>
<footer class="home-footer"><span>Runs on your device. No account needed.</span><span>A modeled vision adapter connects a 668-neuron fly circuit to Microduck.</span></footer>
</div>
</main>
<main id="experiment-page" hidden>
<div class="scene-header"><header class="experiment-heading"><button id="back-home" aria-label="Back to scenes">← Scenes</button><div><h1 id="arena-title">Follow the beacon</h1><p id="scenario-guide">Move the pink beacon. Watch the duck respond.</p></div></header>
<div class="toolbar"><button id="pause" class="primary" data-control disabled>▶ Run</button><button id="step" data-control disabled title="Advance 0.1 seconds, then pause">Step</button><button id="reset" data-control disabled>Reset</button><span id="clock">0.00 s</span><span class="open-scene-label">No time limit</span><span class="toolbar-spacer"></span><button id="focus-mode" aria-pressed="false" title="Give the scene more space. Escape to leave.">Focus</button><button id="edit-setup" data-control disabled>Edit setup</button><button id="tools-button" aria-expanded="false" aria-controls="tools-panel">Advanced</button></div></div>
<div class="lab-layout">
<section class="workspace"><div id="arena" class="arena" aria-label="Simulation stage"><div class="arena-label"><span id="connected-label">Watching Duck 1</span><span id="live">Paused</span></div><div class="view-actions"><button id="follow" aria-pressed="false">Follow camera</button><button id="view">Fit view</button></div><div id="loading" class="loading"><div class="spinner"></div><strong>Loading scene</strong><span id="loading-detail" role="status">Loading the robot model…</span></div><div class="arena-hint" id="interaction-hint">Drag objects to move them · Select a duck to inspect its brain</div></div>
<div id="scene-control-panels" class="scene-control-panels"><details id="brain-mapping-panel" class="workspace-panel" data-panel></details><details id="objects-panel" class="workspace-panel" data-panel><summary>Scene objects <span class="summary-note">Select or add an object</span></summary><div class="panel-content"><div class="object-tray"><div id="scene-objects" class="object-chips" aria-label="Objects in the scene"></div><details id="quick-add" class="app-menu"><summary>Add object</summary><div class="menu-content">${[
    ["duck", "Duck"],
    ["target", "Beacon"],
    ["wall", "Wall"],
    ["ball", "Ball"],
    ["block", "Block"],
  ]
    .map(
      ([id, label]) =>
        `<button data-add-kind="${id}" data-control disabled>${label}</button>`,
    )
    .join(
      "",
    )}<button data-add-preset="pushable-ball" data-control disabled>Pushable ball</button><button data-add-preset="patrol-wall" data-control disabled>Moving wall</button><button data-add-preset="orbit-target" data-control disabled>Orbiting beacon</button><span class="hint">Adding an object restarts this scene.</span></div></details></div>
<div id="prop-actions" class="prop-actions" hidden><span id="prop-label"></span><span class="hint">Move</span><button data-prop-step="left" aria-label="Move selected object left">←</button><button data-prop-step="right" aria-label="Move selected object right">→</button><button data-prop-step="near" aria-label="Move selected object closer">↓</button><button data-prop-step="far" aria-label="Move selected object farther">↑</button><button id="edit-object">Edit</button><button id="delete-object">Remove</button></div>
</div></details><details id="prop-behavior-panel" class="workspace-panel" data-panel hidden></details><section id="guided-lab" class="guided-lab" aria-label="Guided experiment" hidden></section></div>
<div class="stage-settings-rail" role="group" aria-label="Scene settings"><button id="panel-connections" aria-expanded="false" aria-controls="brain-mapping-panel">Brain → duck</button><button id="panel-objects" aria-expanded="false" aria-controls="objects-panel prop-behavior-panel">Objects & physics</button><button id="panel-experiment" aria-expanded="false" aria-controls="experiment-controls">Experiment</button><button id="close-stage-settings" aria-label="Collapse scene settings" hidden>Close settings</button></div><footer class="statusbar"><span id="status">Loading the simulator…</span><span id="cost"></span></footer></section>
<aside id="brain-panel" class="brain-panel" aria-label="Selected duck: brain and vision"><div class="brain-heading"><div><span class="eyebrow">LIVE MONITOR</span><select id="brain-duck" aria-label="Duck to inspect"></select></div><button id="compact-brain" aria-expanded="true" aria-controls="duck-inspector" title="Show a compact brain monitor">Compact</button></div>
<section id="duck-inspector"><section class="vision-card"><div class="eye-heading"><strong>Duck camera</strong><select id="eye-view" aria-label="Displayed eye"><option value="center">Head</option><option value="left">Left</option><option value="right">Right</option></select></div><div class="eye-frame"><canvas id="eye" width="${W}" height="${H}" aria-label="Selected duck camera and optical flow"></canvas><span id="eye-empty">Run the scene to view the camera</span></div><div class="vision-caption"><span id="vision-status">Waiting for a frame</span><label class="inline"><input id="flow-overlay" type="checkbox" checked>Motion overlay</label></div><details class="monitor-controls" id="vision-controls" data-panel><summary>Vision controls</summary><div class="vision-actions"><button id="cover-eyes" aria-pressed="false" data-control disabled>Cover eyes</button><button id="webcam">Use my camera</button></div></details></section>
<section class="neural-card"><div class="neural-heading"><strong>Fly brain</strong><span id="brain-connection">668 neurons · connected</span></div><canvas id="brain-plot" aria-label="Fly circuit neural activity"></canvas><div class="neural-legend"><span>Forward</span><span>Turn</span><span>Stop reflex</span></div><details class="monitor-controls" id="neural-controls" data-panel><summary>Send a signal</summary><canvas id="trace" aria-label="Neural firing history"></canvas><div class="pulse-label">Stimulate a pathway in the fly circuit</div><div class="pulses">${[
    ["walk", "Walk"],
    ["left", "Turn left"],
    ["right", "Turn right"],
    ["loom", "Stop reflex"],
    ["backward", "MDN pulse"],
  ]
    .map(
      ([id, name]) =>
        `<button data-stimulus="${id}" data-control disabled>${name}</button>`,
    )
    .join("")}</div></details></section>
<section class="body-response"><div class="response-heading"><strong id="body-response">Waiting for visual input</strong><button id="inspect-event" title="Inspect the latest action and its inputs">Why?</button></div><div id="loop-readout" class="loop-readout"><span>Brain request <b id="loop-intent">Waiting</b></span><span>Body command <b id="loop-command">0.00 m/s</b></span><span>Measured speed <b id="loop-speed">0.00 m/s</b></span><span>Feedback <b id="loop-feedback">Waiting</b></span></div><p id="loop-reason" class="loop-reason">Run the scene to see what drives each action.</p><details class="monitor-controls" id="body-details" data-panel><summary>Movement & feedback</summary><div class="signal-bars"><div><span>Forward <b id="forward">0 Hz</b></span><meter id="forward-meter" min="0" max="150" value="0" aria-label="Forward neuron activity"></meter></div><div><span>Turn <b id="yaw">0 rad/s</b></span><meter id="turn-meter" min="0" max="0.8" value="0" aria-label="Turn command strength"></meter></div></div><span id="metrics">0.00 m/s · 0.00 m</span><span id="tilt" hidden>0°</span><span id="feet" hidden>L · R</span><p id="feedback-loop" class="feedback-loop"></p><p id="model-note">Modeled vision → fly circuit → duck walking policy</p><button id="duck-settings" aria-label="Edit selected duck">Duck settings</button></details></section></section>
<p class="connection-note">668-neuron fly circuit · modeled vision</p></aside>
<aside id="tools-panel" class="tools-panel" aria-label="Scene tools" hidden><div class="panel-title"><h2>Scene tools</h2><button id="close-tools" aria-label="Close scene tools">Close</button></div><details open id="selected-object-panel" data-panel><summary>Selected object</summary><div class="panel-title"><span id="selection-title">Duck 1</span><button id="remove" aria-label="Remove selected object">Remove</button></div><div id="object-editor"></div><button id="push" data-control disabled>Nudge selected duck</button></details><details class="scene-panel" id="scene-settings-panel" data-panel><summary>Scene settings <span id="object-count"></span></summary><input id="scene-name" aria-label="Scene name" maxlength="80"><div id="scene-tree"></div><div class="add-controls"><select id="add-kind" aria-label="Object to add"><option value="duck">Duck</option><option value="target">Beacon</option><option value="wall">Wall</option><option value="block">Block</option><option value="ball">Ball</option><option value="light">Light field</option><option value="odor">Scent field</option></select><button id="add" data-control disabled>＋ Add</button></div><p class="hint">Changing shapes restarts the scene. Moving objects or changing connections keeps the current positions.</p><details class="challenge"><summary>Goal tracking</summary><label>Track progress for<select id="challenge-subject"></select></label><div class="pair"><label>Goal X · m<input id="goal-x" type="number" step=".1"></label><label>Goal Y · m<input id="goal-y" type="number" step=".1"></label></div><button id="challenge-apply">Apply goal</button><div id="scores"></div></details><details class="challenge"><summary>Research tools</summary><button id="vision-bench">Vision test bench</button><button id="loom-compare" data-control disabled>Looming trials</button><button id="compare" data-control disabled>Compare controllers</button><button id="learn" data-control disabled>Train sensory adapter</button><p class="hint">Tests run in a separate scene. Adapter training is checked on new object placements before any changes are applied.</p></details></details>
<details id="recordings-panel" data-panel><summary>Recordings & replay</summary><section class="timeline"><div class="timeline-head"><strong>Recording</strong><span id="branch-label">Branch 0</span><span class="toolbar-spacer"></span><button id="export" data-control disabled>Export recording</button><button id="branch" data-control disabled>Branch here</button></div><div class="timeline-track"><span id="timeline-start">0 s</span><input id="rewind" aria-label="Rewind to checkpoint" type="range" min="0" max="0" value="0" step="1"><span id="timeline-end">0 s</span></div><p>Rewind to a saved point and change a setting to start a new branch. More ducks reduce the amount of history kept.</p></section>
</details><details><summary>Load another scene</summary><select id="preset" aria-label="Scene preset"><option value="">Choose a scene</option>${SCENARIOS.map((s) => `<option value="${s.id}">${s.title}</option>`).join("")}</select></details></aside>
</div></main><div id="notice" role="status" hidden></div><input id="file" type="file" accept=".json,application/json" hidden>
`;
}
