const $=s=>document.querySelector(s), t=()=>window.duckflyTelemetry;
const wait=async(predicate,timeout=20000)=>{const start=Date.now();while(!predicate()){if(Date.now()-start>timeout)throw Error('Audit timed out: '+JSON.stringify({scene:t()?.scene?.name,time:t()?.time,paused:t()?.paused,notice:$('#notice')?.textContent}));await new Promise(r=>setTimeout(r,20));}};
const check=(condition,message)=>{if(!condition)throw Error(message+' '+JSON.stringify({tick:t()?.tick,paused:t()?.paused,scene:t()?.scene?.name}));};
await wait(()=>t()?.ready);
const scenarios=[...document.querySelectorAll('[data-scenario]')].map(e=>({id:e.dataset.scenario,title:e.querySelector('h3').textContent}));
const result={format:'duckfly-catalog-audit',version:3,scenarios:[],controls:[]};
const sample=()=>{const s=t();return {time:s.time,tick:s.tick,paused:s.paused,loop:s.loop,collisions:s.collisionCount,ducks:s.ducks.map(d=>{const a=s.agents[d.id],v=a?.vision;return {id:d.id,position:d.position,command:d.command,speed:d.speed,distance:d.distance,fallen:d.fallen,tilt:d.tilt,visible:v?.target.visible,neighborVisible:v?.neighbor.visible,area:v?.target.area,pixels:v?.target.candidatePixels,input:a?.input,neural:a?.neural&&{vx:a.neural.vx,yaw:a.neural.yaw,forward:a.neural.forward,spikes:a.neural.spikeCount},temporal:a?.temporal&&{held:a.temporal.held,fresh:a.temporal.fresh,gfEvents:a.temporal.gfEvents}};})};};
for(const scenario of scenarios){
  if($('#home-page').hidden)$('#back-home').click();
  const name=scenario.id==='empty'?'Open arena':scenario.title;
  document.querySelector(`[data-scenario="${scenario.id}"]`).click();
  await wait(()=>t().scene.name===name&&t().time>.05);
  const row={...scenario,samples:[]};
  for(let at=.5;at<=5;at+=.5){await wait(()=>t().tick>=Math.round(at/.02));row.samples.push(sample());}
  if(!t().paused){$('#pause').click();await wait(()=>t().paused);}
  row.final=sample();
  check(row.final.ducks.every(d=>Number.isFinite(d.speed)&&d.command.every(Number.isFinite)),scenario.id+' nonfinite movement');
  check(row.final.ducks.every(d=>!d.fallen),scenario.id+' fell during the default audit');
  result.scenarios.push(row);
  check(!$('#guided-lab').hidden,scenario.id+' is missing scene controls');
  check($('#loop-intent').textContent.length&&$('#loop-command').textContent.length,scenario.id+' missing loop readout');
  const beyond=scenario.id==='target'?1600:300;
  $('#pause').click();await wait(()=>t().tick>=beyond,60000);
  check(!t().paused,scenario.id+' automatically stopped at a time limit');
  row.openEnded=sample();$('#pause').click();await wait(()=>t().paused);
  if(scenario.id==='stop-go')check(!$('#lab-save').hidden,'Five-second observation was not retained in the open scene');
  $('#body-details').open=true;
  $('#motor-link').click();$('#feedback-link').click();
  await wait(()=>!t().scene.ducks[0].motorEnabled&&!t().scene.ducks[0].feedback);
  const tick=t().tick, spikes=t().agents['duck-1'].neural.spikeCount;
  $('#step').click();await wait(()=>t().tick===tick+5&&t().paused);
  check(t().ducks[0].command.every(v=>v===0),scenario.id+' disconnected motor still commanded movement');
  check(t().agents['duck-1'].neural.spikeCount>spikes,scenario.id+' disconnect stopped brain simulation');
  check(t().agents['duck-1'].neural.feedback.drive===0,scenario.id+' feedback disconnect failed');
  result.controls.push({id:scenario.id,disconnected:sample(),actions:[...$('#guided-lab').querySelectorAll('[data-lab-action]')].filter(e=>!e.closest('[hidden]')).map(e=>e.dataset.labAction)});
  $('#motor-link').click();$('#feedback-link').click();
  await wait(()=>t().scene.ducks[0].motorEnabled&&t().scene.ducks[0].feedback);
  $('#motor-gain').value='0.5';$('#motor-gain').dispatchEvent(new Event('change',{bubbles:true}));
  await wait(()=>t().scene.ducks[0].motorGain===.5);
  $('#step').click();await wait(()=>t().tick===tick+10&&t().paused);
  check(Math.abs(t().ducks[0].command[0])<=.15+1e-9,scenario.id+' gain was ignored');
  result.controls.at(-1).reconnected=sample();
}
$('#back-home').click();document.querySelector('[data-scenario="target"]').click();await wait(()=>t().scene.name==='Follow the beacon'&&t().time>.05);
$('#pause').click();await wait(()=>t().paused);
$('#scene-objects [data-object="target-1"]').click();$('#edit-object').click();
const set=(selector,value)=>{const el=$(selector);el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));};
// Use the actual editor fields. The regression is a cue moved beyond the original recognizer's range.
const fields=[...$('#object-editor').querySelectorAll('input[type="number"]')];
fields[0].value='1.63';fields[1].value='0';$('#apply-object').click();
await wait(()=>t().time===0&&Math.abs(t().scene.props[0].position[0]-1.63)<.001);
$('#close-tools').click();$('#pause').click();await wait(()=>t().tick>=150);$('#pause').click();await wait(()=>t().paused);
result.farBeacon=sample();
check(t().ducks[0].command[0]===0,'Distant target should be gated in the frozen recognizer');
check($('#vision-status').textContent.includes('too small'),'Tiny cue lacks a useful diagnosis');
$('[data-lab-action="beacon-ahead"]').click();
await wait(()=>Math.abs(t().scene.props[0].position[0]-1.63)>.1);
const before=t().ducks[0].distance;$('#pause').click();await wait(()=>t().tick>=300);$('#pause').click();await wait(()=>t().paused);
result.recoveredBeacon=sample();
check(t().ducks[0].distance-before>.15,'Bring beacon ahead did not restore physical walking');
$('#vision-controls').open=true;$('#cover-eyes').click();await wait(()=>t().scene.ducks[0].eye==='none');
const tick=t().tick;$('#step').click();await wait(()=>t().tick===tick+5);
check(t().ducks[0].command[0]===0,'Covered eyes must block following');
result.covered=sample();
$('[data-stimulus="walk"]').click();await new Promise(r=>setTimeout(r,100));
check(t().paused&&t().tick===tick+5,'Queued pulse advanced a paused clock');
check($('#notice').textContent.includes('queued'),'Queued pulse had no explanation');
// Apply motion without restarting the clock or neural state, then switch to real gravity.
$('#back-home').click();document.querySelector('[data-scenario="target"]').click();
await wait(()=>t().scene.name==='Follow the beacon'&&t().tick>5&&t().tick<50&&!t().paused);$('#pause').click();await wait(()=>t().paused);
$('#scene-objects [data-object="target-1"]').click();
const choose=(id,value)=>{const el=$(id);el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}));};
const motionTick=t().tick;
choose('#prop-profile','patrol');$('#apply-behavior').click();await wait(()=>t().scene.props[0].behavior?.kind==='patrol');
check(t().tick===motionTick,'Adding a motion path reset the clock');
const startPosition=[...t().props[0].position];$('#pause').click();await wait(()=>t().tick>=motionTick+100);$('#pause').click();await wait(()=>t().paused);
check(Math.abs(t().props[0].position[1]-startPosition[1])>.1,'Patrol did not move the physical prop');
result.patrol={time:t().time,prop:t().props[0],definition:t().scene.props[0]};
choose('#prop-profile','orbit');const orbitTick=t().tick;$('#apply-behavior').click();await wait(()=>t().scene.props[0].behavior?.kind==='orbit');
check(t().tick===orbitTick,'Changing motion restarted the scene');
choose('#prop-profile','pushable');check($('#apply-behavior').textContent.includes('restart'),'Physics restart not explained');
$('#apply-behavior').click();await wait(()=>t().tick===0&&t().scene.props[0].movable);
$('#pause').click();await wait(()=>t().tick>=50);$('#pause').click();await wait(()=>t().paused);
check(t().props[0].position[2]<.08,'A pushable body did not fall under gravity');
result.pushable={prop:t().props[0],definition:t().scene.props[0]};
choose('#prop-profile','heavy');$('#apply-behavior').click();await wait(()=>t().tick===0&&t().scene.props[0].mass===1);
check(t().scene.props[0].behavior===null,'Free body retained an animated path');
result.heavy=t().scene.props[0];
return result;
