const $ = selector => document.querySelector(selector);
const t = () => window.duckflyTelemetry;
const clone = value => JSON.parse(JSON.stringify(value));
const check = (condition, message) => { if (!condition) throw Error(message); };
const receipts = [];
let stage = 'initialization';
const wait = async (predicate, timeout = 35000) => {
  const start = Date.now();
  while (!predicate()) {
    if (Date.now() - start > timeout)
      throw Error('Setup acceptance timed out at ' + stage + ': ' + JSON.stringify({tick:t()?.tick, scene:t()?.scene?.name, paused:t()?.paused, notice:$('#notice')?.textContent, setupOpen:$('#scene-setup')?.open, setupError:$('#setup-error')?.textContent}));
    await new Promise(resolve => setTimeout(resolve, 20));
  }
};
const change = (selector, value) => {
  const element = $(selector);
  check(element, 'Missing control ' + selector);
  if (element.type === 'checkbox') element.checked = value;
  else element.value = String(value);
  element.dispatchEvent(new Event('change', {bubbles:true}));
};
const action = name => {
  const button = $(`[data-setup-action="${name}"]`);
  check(button && !button.hidden && !button.disabled, 'Setup action unavailable: ' + name);
  button.click();
};
// Functional acceptance checks computed DOM layout even if a locked display
// suspends painting. Visible browser screenshots cover the actual rendered UI.
const settle = async () => {
  await new Promise(resolve => setTimeout(resolve, 50));
  $('#experiment-page').getBoundingClientRect();
};
const physicalState = () => JSON.stringify({tick:t().tick, scene:t().scene, ducks:t().ducks, agents:t().agents});
const inView = selector => {
  const r = $(selector).getBoundingClientRect();
  return r.width > 0 && r.height > 0 && r.top >= 0 && r.bottom <= innerHeight && r.left >= 0 && r.right <= innerWidth;
};
const openTile = async id => {
  await enterSceneCatalog();
  $(`[data-customize-scenario="${id}"]`).click();
  await wait(() => $('#scene-setup')?.open && t().paused);
};
let downloadPromise;
const originalAnchorClick = HTMLAnchorElement.prototype.click;
const originalConsoleError = console.error;
const errors = [];
const onError = event => errors.push(String(event.error?.stack || event.message));
const onRejection = event => errors.push(String(event.reason?.stack || event.reason));
window.addEventListener('error', onError);
window.addEventListener('unhandledrejection', onRejection);
console.error = (...args) => { errors.push(args.map(String).join(' ')); originalConsoleError.apply(console, args); };
HTMLAnchorElement.prototype.click = function () {
  if (this.download) downloadPromise = fetch(this.href).then(response => response.json());
  else originalAnchorClick.call(this);
};
const exportJSON = async selector => {
  downloadPromise = null;
  $(selector).click();
  await wait(() => downloadPromise);
  return downloadPromise;
};
const importJSON = async value => {
  const transfer = new DataTransfer();
  transfer.items.add(new File([JSON.stringify(value)], 'setup-test.json', {type:'application/json'}));
  $('#file').files = transfer.files;
  $('#file').dispatchEvent(new Event('change', {bubbles:true}));
};

try {
  await wait(() => t()?.ready);
  await enterSceneCatalog();
  check(!$('#home-page').hidden && $('#experiment-page').hidden, 'App did not begin at scenario tiles');
  stage = 'new scene entry from the dashboard'; reportAcceptanceStage(stage);
  check(inView('#new-scene') && !$('#new-scene').disabled, 'New scene is not available at the top of the dashboard');
  const beforeNew = physicalState();
  $('#new-scene').click();
  await wait(() => $('#scene-setup')?.open);
  check($('#setup-title').textContent === 'Blank scene', 'New scene did not open a fresh playground');
  check(document.querySelectorAll('#scene-setup [data-setup-select]').length === 1, 'New scene inherited the previous scene members');
  action('add-duck');
  action('cancel');
  await wait(() => !$('#scene-setup').open);
  check(physicalState() === beforeNew && !$('#home-page').hidden, 'Cancelling a new scene changed the dashboard experiment');
  await wait(() => document.activeElement === $('#new-scene'));
  receipts.push({check:'top dashboard New scene opens an isolated playground and restores focus after cancellation'});
  stage = 'draft cancellation'; reportAcceptanceStage(stage);
  const initial = physicalState();
  await openTile('target');
  check(physicalState() === initial, 'Opening a tile started or replaced the scene before review');
  action('add-duck');
  action('next');
  change('#setup-forward', 'off');
  await new Promise(resolve => setTimeout(resolve, 160));
  check(physicalState() === initial, 'Draft changes leaked into the retained experiment');
  action('cancel');
  await wait(() => !$('#scene-setup').open);
  check(physicalState() === initial && !$('#home-page').hidden, 'Cancelling changed the retained scene or screen');
  receipts.push({check:'tile opens isolated setup; cancellation preserves the scene and neural state'});

  stage = 'build a scene through the wizard'; reportAcceptanceStage(stage);
  await openTile('target');
  action('add-duck');
  change('[data-setup-path="name"]', 'Observer');
  change('[data-setup-path="spawn.0"]', 0);
  change('[data-setup-path="spawn.1"]', -.35);
  change('[data-setup-path="spawn.2"]', 0);
  action('next');
  change('#setup-duck-select', 'duck-2');
  change('#setup-forward', 'off');
  change('#setup-turn', 'off');
  change('#setup-duck-select', 'duck-1');
  check($('#setup-forward').value === 'walk' && $('#setup-turn').value === 'follow', 'Editing the second duck rewired the first duck');
  const advanced = $('[data-setup-panel="advanced-brain"]');
  advanced.open = true;
  const weights = advanced.querySelector('details');
  weights.open = false;
  const source = $('[data-setup-path="source"]');
  source.focus();
  $('#setup-controls').scrollTop = 190;
  const requestedScroll = $('#setup-controls').scrollTop;
  // A no-edit control separates WebKit's deferred focus scroll from an edit.
  await settle();
  const focusOnlyScroll = $('#setup-controls').scrollTop;
  reportAcceptanceStage('focus scroll control '+JSON.stringify({requestedScroll,focusOnlyScroll}));
  $('#setup-controls').scrollTop = 190;
  await settle();
  const brainScroll = $('#setup-controls').scrollTop;
  check(brainScroll > 0, 'Advanced wizard acceptance did not reach a scrollable form');
  change('[data-setup-path="source"]', 'webcam');
  await settle();
  check(Math.abs($('#setup-controls').scrollTop - brainScroll) < 2, 'Editing an advanced select jumped the setup form '+JSON.stringify({requestedScroll,focusOnlyScroll,before:brainScroll,after:$('#setup-controls').scrollTop,sameControl:source===$('[data-setup-path="source"]')}));
  check($('[data-setup-panel="advanced-brain"]').open, 'An open advanced section collapsed after a select edit');
  change('[data-setup-path="source"]', 'eyes');
  change('#setup-feedback', false);
  await settle();
  check(Math.abs($('#setup-controls').scrollTop - brainScroll) < 2, 'Editing a checkbox jumped the setup form');
  check(!$('[data-setup-panel="adapter-weights"]').open, 'A closed advanced section reopened after a control edit');
  change('#setup-feedback', true);
  action('next');
  $('[data-add-prop="ball"]').click();
  change('#setup-prop-profile', 'heavy');
  change('[data-setup-path="position.0"]', .25);
  change('[data-setup-path="position.1"]', 1.15);
  change('[data-setup-path="position.2"]', .28);
  const ballMapId = $('#scene-setup .setup-entity.is-selected').dataset.setupSelect;
  const mapItem = $(`[data-map-entity="${ballMapId}"]`);
  mapItem.focus();
  mapItem.dispatchEvent(new KeyboardEvent('keydown', {key:'ArrowRight', bubbles:true}));
  check(Number($('[data-setup-path="position.0"]').value) === .3, 'The visual map did not edit the selected object position');
  change('[data-setup-path="position.0"]', .25);
  change('[data-setup-path="mass"]', 0);
  const invalidSelection = $('#scene-setup .setup-entity.is-selected').dataset.setupSelect;
  const invalidCount = document.querySelectorAll('#scene-setup .setup-entity').length;
  $('[data-setup-select="target-1"]').click();
  check($('#scene-setup .setup-entity.is-selected').dataset.setupSelect === invalidSelection && $('[data-setup-path="mass"]').value === '0', 'Selecting another object discarded an invalid unfinished weight');
  $('[data-add-prop="block"]').click();
  check(document.querySelectorAll('#scene-setup .setup-entity').length === invalidCount && $('[data-setup-path="mass"]').value === '0', 'Adding an object discarded an invalid unfinished weight');
  const invalidMapX = $('[data-setup-path="position.0"]').value;
  $(`[data-map-entity="${ballMapId}"]`).dispatchEvent(new KeyboardEvent('keydown', {key:'ArrowRight', bubbles:true}));
  check($('[data-setup-path="mass"]').value === '0' && $('[data-setup-path="position.0"]').value === invalidMapX, 'Moving on the map discarded invalid physics');
  action('next');
  check($('[data-setup-step="2"]'), 'Invalid object physics passed the wizard validation');
  change('[data-setup-path="mass"]', 1);
  const physicalDetails = $('[data-setup-panel="object-physics"]');
  physicalDetails.open = false;
  change('#setup-prop-profile', 'pushable');
  check(!$('[data-setup-panel="object-physics"]').open, 'A closed physical-properties section reopened when behavior changed');
  change('#setup-prop-profile', 'heavy');
  const nameInput = $('[data-setup-path="name"]');
  nameInput.value = 'Practice ball';
  nameInput.dispatchEvent(new Event('input', {bubbles:true}));
  action('next');
  check($('#setup-review').textContent.includes('Observer') && $('#setup-review').textContent.includes('Practice ball'), 'Review omitted added scene members');
  check(physicalState() === initial, 'Review advanced the old simulation');
  $('#setup-scene-name').value = 'Wizard loop study';
  $('#setup-scene-name').dispatchEvent(new Event('input', {bubbles:true}));
  action('apply');
  await wait(() => !$('#scene-setup').open && t().ducks.length === 2 && t().tick >= 150 && !t().paused);
  $('#pause').click();
  await wait(() => t().paused);
  const initialRun = clone(t());
  const ball = t().scene.props.find(p => p.name === 'Practice ball');
  check(t().scene.name === 'Wizard loop study', 'Apply lost the experiment name entered before the click');
  check(t().scene.version === 9, 'An explicit mapping was not saved in scene schema 9');
  check(ball?.movable && ball.mass === 1 && t().props.find(p => p.id === ball.id).position[2] < .1, 'Upfront heavy-body physics did not reach MuJoCo gravity');
  check(t().ducks.every(d => !d.fallen), 'The configured scene fell during its initial run');
  check(t().ducks.find(d => d.id === 'duck-1').distance > .1, 'The default vision-to-walking path did not move the first duck');
  const initialRecording = await exportJSON('#export');
  const firstCommands = initialRecording.events.flatMap(e => e.causes.filter(c => c.id === 'duck-1'));
  const secondCommands = initialRecording.events.flatMap(e => e.causes.filter(c => c.id === 'duck-2'));
  check(firstCommands.some(c => c.command.vx > .2), 'No walking command reached the first duck');
  check(secondCommands.length > 50 && secondCommands.every(c => c.command.vx === 0 && c.command.yaw === 0), 'Disconnected mappings leaked movement commands');
  check(secondCommands.some(c => c.neural.forward > 6), 'The second duck’s circuit was stopped instead of disconnecting its body mapping');
  receipts.push({check:'wizard mappings reach independent neural controllers; added heavy ball falls under gravity', duck1Distance:initialRun.ducks[0].distance, deliveredEvents:secondCommands.length, ballHeight:t().props.find(p => p.id === ball.id).position[2]});
  receipts.push({check:'invalid unfinished physics survives select/add attempts; advanced controls preserve scroll and collapsed sections', advancedScroll:brainScroll});

  stage = 'edit setup without restarting for a mapping change'; reportAcceptanceStage(stage);
  change('#brain-duck', 'duck-2');
  const beforeEdit = clone(t());
  $('#edit-setup').click();
  await wait(() => $('#scene-setup').open);
  check($('[data-setup-select="duck-2"]'), 'Later setup did not retain the added duck');
  action('next');
  change('#setup-duck-select', 'duck-2');
  check($('#setup-forward').value === 'off' && $('#setup-turn').value === 'off', 'Later setup did not retain the mapping');
  change('#setup-forward', 'walk');
  change('#setup-turn', 'follow');
  action('next');
  $(`[data-setup-select="${ball.id}"]`).click();
  check($('#setup-prop-profile').value === 'heavy', 'Later setup did not retain object physics');
  action('next');
  action('apply');
  await wait(() => !$('#scene-setup').open && t().scene.ducks[1].mapping.forward === 'walk');
  check(t().paused && t().tick === beforeEdit.tick, 'Editing only mappings restarted or resumed a paused scene');
  check(JSON.stringify(t().ducks) === JSON.stringify(beforeEdit.ducks) && JSON.stringify(t().agents['duck-1']) === JSON.stringify(beforeEdit.agents['duck-1']), 'Mapping-only setup edited the other brain or physical world');

  stage = 'live selected-duck controls'; reportAcceptanceStage(stage);
  $('#panel-connections').click();
  await settle();
  check($('#brain-mapping-panel').open, 'The connection rail did not open its settings panel');
  check($('#mapping-forward').value === 'walk' && $('#mapping-turn').value === 'follow', 'Live settings did not reflect setup changes');
  change('#mapping-forward', 'off');
  await wait(() => t().scene.ducks[1].mapping.forward === 'off');
  check(t().scene.ducks[0].mapping.forward === 'walk' && t().tick === beforeEdit.tick, 'Live edit changed another duck or reset the clock');
  change('#brain-duck', 'duck-1');
  check($('#mapping-forward').value === 'walk', 'Selected-duck mapping did not switch with the monitored brain');
  change('#brain-duck', 'duck-2');
  check($('#mapping-forward').value === 'off', 'Second duck lost its independently edited mapping');
  change('#mapping-forward', 'walk');
  await wait(() => t().scene.ducks[1].mapping.forward === 'walk');
  const secondBefore = t().ducks.find(d => d.id === 'duck-2').distance;
  const resumedAt = t().tick;
  $('#pause').click();
  await wait(() => t().tick >= resumedAt + 100);
  $('#pause').click();
  await wait(() => t().paused);
  const secondDistance = t().ducks.find(d => d.id === 'duck-2').distance - secondBefore;
  check(secondDistance > .025, 'Reconnecting the second duck did not produce physical movement');
  check(t().ducks.every(d => !d.fallen), 'Live mapping change caused a fall');
  receipts.push({check:'later setup and live controls stay synchronized; mapping-only changes preserve time and the other brain', secondDuckMovement:secondDistance});

  stage = 'save and reload exact mappings and runtime'; reportAcceptanceStage(stage);
  const saved = clone(t());
  const sceneFile = await exportJSON('#save');
  check(sceneFile.version === 9 && JSON.stringify(sceneFile.ducks.map(d => d.mapping)) === JSON.stringify(saved.scene.ducks.map(d => d.mapping)), 'Scene export lost the versioned mappings');
  const recording = await exportJSON('#export');
  check(recording.format === 'duckfly-recording' && recording.version >= 4 && recording.checkpoint.scene.version === 9, 'Recording did not retain a versioned mapping scene');
  $('#reset').click();
  await wait(() => t().tick === 0);
  await importJSON(sceneFile);
  await wait(() => t().tick === 0 && JSON.stringify(t().scene) === JSON.stringify(sceneFile));
  await importJSON(recording);
  await wait(() => t().tick === saved.tick);
  check(JSON.stringify(t().ducks) === JSON.stringify(saved.ducks) && JSON.stringify(t().agents) === JSON.stringify(saved.agents) && JSON.stringify(t().scene) === JSON.stringify(saved.scene), 'Recording roundtrip changed physical state, neural state, or settings');
  receipts.push({check:'scene schema 9 and recording preserve mappings, props, complete neural state, and physical state', sceneVersion:sceneFile.version, recordingVersion:recording.version, tick:saved.tick});

  stage = 'immersive panel layout'; reportAcceptanceStage(stage);
  const beforePresentation = physicalState();
  if ($('#brain-mapping-panel').open) $('#panel-connections').click();
  $('#compact-brain').click();
  await settle();
  check(inView('#eye') && inView('#brain-plot'), 'Collapsing the monitor hid the connected brain or eyesight');
  $('#focus-mode').click();
  await settle();
  check(document.body.classList.contains('focus-mode'), 'Focus mode did not open');
  check(inView('#eye') && inView('#brain-plot'), 'Focus mode hid the connected brain or eyesight');
  check(physicalState() === beforePresentation, 'Panel changes mutated the experiment');
  document.dispatchEvent(new KeyboardEvent('keydown', {key:'Escape', bubbles:true, cancelable:true}));
  await settle();
  check(!document.body.classList.contains('focus-mode'), 'Escape did not restore the editing workspace');
  receipts.push({check:'computed DOM layout keeps brain and eyes inside the viewport when controls collapse or focus mode opens; no experiment change', nativePaintVerified:false});

  stage = 'cancel from a running scene'; reportAcceptanceStage(stage);
  $('#pause').click();
  await wait(() => !t().paused && t().tick > saved.tick);
  $('#edit-setup').click();
  await wait(() => $('#scene-setup').open && t().paused);
  const retained = clone(t());
  action('add-duck');
  await new Promise(resolve => setTimeout(resolve, 120));
  check(t().tick === retained.tick && JSON.stringify(t().scene) === JSON.stringify(retained.scene), 'Running scene kept advancing or adopted the draft');
  action('cancel');
  await wait(() => !$('#scene-setup').open && !t().paused && t().tick > retained.tick);
  check(JSON.stringify(t().scene) === JSON.stringify(retained.scene) && t().ducks.length === 2, 'Cancelling failed to resume the original scene');
  $('#pause').click();
  await wait(() => t().paused);
  receipts.push({check:'cancelling setup resumes a previously running scene with its original objects'});
  stage = 'rapid cancel and reopen preserves run intent'; reportAcceptanceStage(stage);
  $('#pause').click(); await wait(() => !t().paused);
  $('#new-scene').click(); await wait(() => $('#scene-setup').open && t().paused);
  const rapidRetained = clone(t());
  action('cancel');
  // Reopen before the worker can acknowledge the queued resume. This is the
  // same rapid New scene interaction, not an artificial pause inserted by UI.
  $('#new-scene').click();
  check($('#scene-setup').open, 'New scene could not reopen immediately after cancellation');
  action('cancel');
  await wait(() => !$('#scene-setup').open && !t().paused && t().tick > rapidRetained.tick);
  check(JSON.stringify(t().scene) === JSON.stringify(rapidRetained.scene) && t().connectedDuck === rapidRetained.connectedDuck, 'Rapid cancellation replaced the retained scene or selected brain');
  $('#pause').click(); await wait(() => t().paused);
  receipts.push({check:'rapid cancel, reopen, cancel resumes the original scene before a worker resume acknowledgement'});
  stage = 'new scene from a running experiment'; reportAcceptanceStage(stage);
  $('#pause').click();
  await wait(() => !t().paused);
  check(inView('#new-scene'), 'New scene is not available above the running stage');
  $('#new-scene').click();
  await wait(() => $('#scene-setup').open && t().paused);
  const retainedNew = clone(t());
  check($('#setup-title').textContent === 'Blank scene', 'The stage New scene button edited the current experiment');
  action('next'); action('next');
  check(!$('#scene-setup .setup-entity'), 'New scene kept the previous props');
  $('[data-add-prop="block"]').click();
  action('cancel');
  await wait(() => !$('#scene-setup').open && !t().paused && t().tick > retainedNew.tick);
  check(JSON.stringify(t().scene) === JSON.stringify(retainedNew.scene) && t().connectedDuck === retainedNew.connectedDuck, 'Cancelling New scene lost the running scene or selected brain');
  $('#pause').click(); await wait(() => t().paused);
  $('#new-scene').click();
  await wait(() => $('#scene-setup').open);
  action('next');
  change('#setup-mode', 'target');
  change('#setup-forward', 'walk');
  change('#setup-turn', 'follow');
  action('next');
  $('[data-add-prop="target"]').click();
  change('[data-setup-path="position.0"]', .65);
  change('[data-setup-path="position.1"]', 0);
  change('[data-setup-path="position.2"]', .13);
  action('next');
  check($('#setup-review').textContent.includes('Walk'), 'Fresh scene review omitted its chosen walking connection');
  action('apply');
  await wait(() => !$('#scene-setup').open && t().scene.name === 'Blank scene' && t().tick >= 120 && !t().paused);
  $('#pause').click(); await wait(() => t().paused);
  check(t().ducks.length === 1 && t().scene.props.length === 1 && t().scene.props[0].kind === 'target', 'New scene launch leaked retained objects');
  check(t().ducks[0].distance > .1 && !t().ducks[0].fallen, 'A newly created beacon scene did not move through its configured brain connection');
  receipts.push({check:'stage New scene cancellation resumes the prior scene; a fresh beacon and brain mapping run through real vision and physics', distance:t().ducks[0].distance, tick:t().tick});
  check(errors.length === 0, 'Console or uncaught errors: ' + errors.join('\n'));
  return {format:'duckfly-native-setup', version:1, passed:true, checks:receipts, errors};
} finally {
  HTMLAnchorElement.prototype.click = originalAnchorClick;
  console.error = originalConsoleError;
  window.removeEventListener('error', onError);
  window.removeEventListener('unhandledrejection', onRejection);
}
