import './style.css';
import { fetchBytes } from './assets.js';
import { BrainPlot,trace } from './plots.js';
import { LabArena } from './lab/lab-arena.js';
import { ExperimentRoom } from './lab/room.js';
import { defaultScene,validateScene,encodeScene,decodeScene } from './lab/scene.js';
import { EYE_WIDTH as W,EYE_HEIGHT as H } from './lab/vision.js';
const $=s=>document.querySelector(s),escapeHTML=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let scene=defaultScene(),selected='duck-1',arena,plot,state,ready=false,paused=true,stream,video,webcamError='',lastPixels={},samples=[];
try{const encoded=new URLSearchParams(location.hash.slice(1)).get('scene');if(encoded)scene=decodeScene(encoded);else if(localStorage.getItem('duckfly.scene.v1'))scene=validateScene(JSON.parse(localStorage.getItem('duckfly.scene.v1')));}catch(e){webcamError=e.message;}
$('#app').innerHTML=`
<header class="topbar"><a class="brand" href="/" aria-label="DuckFly home"><img src="/duck.svg" alt="">DuckFly <small>EXPERIMENT WORKSPACE</small></a><span class="platform" id="platform">Local simulation</span><div class="top-actions"><button id="room-button">Collaborate</button><button id="share">Share scene</button><button id="save">Save</button><button id="open">Open</button><button id="about" aria-label="About the experiment">ⓘ</button></div></header>
<div class="toolbar"><select id="preset" aria-label="Experiment preset"><option value="">Choose an experiment</option><option value="target">Follow the beacon</option><option value="occlusion">Out of sight</option><option value="loom">Approaching threat</option><option value="flock">Follow the flock</option><option value="empty">Open arena</option></select><span class="divider"></span><button id="pause" class="primary" data-control disabled>▶ Run</button><button id="reset" data-control disabled>↺ Reset</button><span id="clock">0.00 s</span><span class="toolbar-spacer"></span><button id="follow" aria-pressed="false">Follow</button><button id="view">Fit view</button><button id="webcam">Enable webcam</button></div>
<main class="lab-layout">
<aside class="scene-panel"><div class="panel-title">Scene <span id="object-count"></span></div><input id="scene-name" aria-label="Scene name" maxlength="80"><div id="scene-tree"></div><div class="add-controls"><select id="add-kind" aria-label="Object to add"><option value="duck">Duck</option><option value="target">Target</option><option value="wall">Wall</option><option value="block">Block</option><option value="ball">Ball</option><option value="light">Light field</option><option value="odor">Odor field</option></select><button id="add" data-control disabled>＋ Add</button></div><p class="hint">Shape edits restart the arena. Move props or change controllers to branch from the current state.</p><details class="challenge"><summary>Challenge</summary><label>Score object<select id="challenge-subject"></select></label><label>Duration <input id="duration" type="number" min="1" max="600" step="1"> s</label><div class="pair"><label>Goal X<input id="goal-x" type="number" step=".1"></label><label>Goal Y<input id="goal-y" type="number" step=".1"></label></div><button id="challenge-apply">Apply goal</button><div id="scores"></div></details><details class="challenge"><summary>Experiment tools</summary><button id="compare" data-control disabled>Compare controllers</button><button id="learn" data-control disabled>Learn sensory adapter</button><p class="hint">Runs isolated camera-based trials. Learning is checked on held-out placements before changing the adapter.</p></details><div class="scene-foot"><span class="dot"></span>Physics on this device<br><small>MuJoCo · 14 actuators per duck</small></div></aside>
<section class="workspace"><div id="arena" class="arena" aria-label="Physical experiment arena"><div class="arena-label"><span id="arena-title"></span><span id="live">Paused</span></div><div id="loading" class="loading"><div class="spinner"></div><strong>Preparing the experiment</strong><span id="loading-detail" role="status">Loading robot geometry</span></div><div class="arena-hint">Drag props to move · Drag floor to orbit</div></div>
<div class="event-row"><button id="inspect-event" title="Inspect the latest causal event">Waiting for a stimulus</button><span id="metrics">0.00 m/s · 0.00 m</span></div>
<section class="timeline"><div class="timeline-head"><strong>Recording</strong><span id="branch-label">Branch 0</span><span class="toolbar-spacer"></span><button id="export" data-control disabled>Export recording</button><button id="branch" data-control disabled>Branch here</button></div><div class="timeline-track"><span id="timeline-start">0 s</span><input id="rewind" aria-label="Rewind to checkpoint" type="range" min="0" max="0" value="0" step="1"><span id="timeline-end">0 s</span></div><p>Rewind to a checkpoint, then change a cue or controller to branch. Recent history retained; the window scales with duck count.</p></section>
<footer class="statusbar"><span id="status">Loading local engines</span><span id="cost"></span></footer></section>
<aside class="inspector"><div class="panel-title"><span id="selection-title">Duck 1</span><button id="remove" aria-label="Remove selected object">Remove</button></div><div id="object-editor"></div><section id="duck-inspector"><div class="eye-heading"><strong>Camera input</strong><label class="inline"><input id="flow-overlay" type="checkbox" checked>Flow</label></div><canvas id="eye" width="${W}" height="${H}" aria-label="Selected duck camera and optical flow"></canvas><div id="vision-status" class="hint">Run to sample the camera</div><div class="metrics-grid"><div>Forward<strong id="forward">0 Hz</strong></div><div>Turn intent<strong id="yaw">0 rad/s</strong></div><div>Body tilt<strong id="tilt">0°</strong></div><div>Feet<strong id="feet">L · R</strong></div></div><details open><summary>Stimulate the circuit</summary><div class="pulses">${[['walk','↑ Walk'],['loom','◎ Loom'],['left','↰ Left'],['right','↱ Right']].map(([id,name])=>`<button data-stimulus="${id}" data-control disabled>${name}</button>`).join('')}</div><button id="push" data-control disabled>Nudge body</button></details><details><summary>Neural activity</summary><canvas id="brain-plot" aria-label="Fly circuit neural activity"></canvas><canvas id="trace" aria-label="Neural firing history"></canvas><p class="hint">668-neuron circuit. Sensory mappings and social drives are modeled additions.</p></details></section></aside>
</main><div id="notice" role="status" hidden></div><input id="file" type="file" accept=".json,application/json" hidden>
<dialog id="room-dialog"><div class="dialog-top"><strong>Collaborative experiment</strong><button data-close="room-dialog" aria-label="Close collaboration">✕</button></div><p id="room-status">Pair one collaborator. The host runs the shared world; both people can edit props and controllers.</p><div class="pair"><button id="room-host">Create invitation</button><button id="room-join">Join with invitation</button></div><label>Invitation or reply<textarea id="room-input" rows="3" spellcheck="false" placeholder="Paste a pairing code"></textarea></label><button id="room-accept">Accept collaborator reply</button><label>Your pairing code<textarea id="room-output" rows="3" readonly spellcheck="false"></textarea></label><button id="room-copy">Copy pairing code</button><button id="room-leave">Leave room</button><details><summary>Connection settings</summary><p class="hint">Direct WebRTC connection. If your networks require a relay, supply a TURN server. Pair again after a disconnect. Webcam frames are not shared.</p><label>TURN server<input id="turn-url" placeholder="turn:your-server:3478"></label><div class="pair"><label>Username<input id="turn-user" autocomplete="off"></label><label>Password<input id="turn-password" type="password" autocomplete="off"></label></div></details></dialog><dialog id="job-dialog"><div class="dialog-top"><strong id="job-title">Experiment batch</strong><button id="cancel-job">Cancel</button></div><p id="job-progress">Preparing isolated trials</p><progress id="job-meter" max="1" value="0"></progress><div id="job-results"></div><button id="save-report" hidden>Save report</button><button id="close-job" hidden>Close</button></dialog><dialog id="event-dialog"><div class="dialog-top"><strong>Causal inspector</strong><button data-close="event-dialog" aria-label="Close causal inspector">✕</button></div><p id="event-time"></p><div id="event-content"></div><label>Recorded event <input id="event-index" type="range" min="0" max="0" value="0"></label></dialog>
<dialog id="about-dialog"><div class="dialog-top"><strong>About DuckFly</strong><button data-close="about-dialog" aria-label="Close about">✕</button></div><h2>A small circuit in a physical world.</h2><p>Camera pixels become sensory signals for DesktopFly’s 668-neuron FlyWire circuit. Neural activity selects movement intent, and Microduck’s pretrained policy controls the joints. MuJoCo and BAM calculate the physical response.</p><p>The sensory adapters are modeling assumptions. This is not a complete fly nervous system, and the connectome has not learned biped balance. Each duck has independent neural state in a shared physical arena.</p><p>Webcam access is optional. Camera frames stay on this device; exported recordings include the low-resolution frames used by the experiment.</p><p><a href="https://github.com/DenisSergeevitch/desktop-fly" target="_blank" rel="noreferrer">DesktopFly</a> · <a href="https://github.com/pollen-robotics/microduck_rl" target="_blank" rel="noreferrer">Microduck RL</a></p><p class="hint">FlyWire data is CC BY-NC 4.0. <a href="/assets/THIRD_PARTY_NOTICES.md" target="_blank">Source and license notices</a>.</p></dialog>`;
let lastReport,room,jobBusy=false,lastRoomSent=0,remoteSceneKey,pendingPropMove;
const worker=new Worker(new URL('./lab/lab.worker.js',import.meta.url),{type:'module'});
const remoteActions=new Set(['scene','duck','move-prop','stimulus','push']);
const send=(type,extra={})=>{if(room?.role==='guest'){if(remoteActions.has(type)){if(!room.command({type,...extra}))notify('Room is disconnected. Pair again to send edits.');}else notify('The host controls the simulation clock and recordings.');return;}worker.postMessage({type,...extra});};
if(window.duckflyHost)$('#platform').textContent='Mac · local simulation';
function persistScene(){localStorage.setItem('duckfly.scene.v1',JSON.stringify(scene));window.webkit?.messageHandlers?.scene?.postMessage(scene);}
const current=()=>scene.ducks.find(d=>d.id===selected)??scene.props.find(p=>p.id===selected)??scene.fields.find(f=>f.id===selected);
function notify(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').hidden=true,7000);}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function sceneChanged(next){try{scene=validateScene(next);send('scene',{scene});persistScene();}catch(e){notify(e.message);}}
function selectObject(id){selected=id;arena.selected=scene.ducks.some(d=>d.id===id)?id:scene.ducks[0].id;renderScene();renderInspector();samples=[];drawEye();}
function renderScene(){
  $('#scene-name').value=scene.name;$('#arena-title').textContent=scene.name;$('#object-count').textContent=scene.ducks.length+scene.props.length+scene.fields.length;
  $('#scene-tree').innerHTML=[['Ducks',scene.ducks],['Props',scene.props],['Sensory fields',scene.fields]].map(([label,items])=>`<div class="tree-group">${label}</div>${items.map(o=>`<button class="tree-item" data-object="${o.id}" aria-pressed="${o.id===selected}"><span>${scene.ducks.includes(o)?'◈':o.kind==='light'?'☀':o.kind==='odor'?'◌':'◇'}</span><span>${escapeHTML(o.name??o.kind)}</span><small>${escapeHTML(o.mode??o.kind)}</small></button>`).join('')}`).join('');
  document.querySelectorAll('[data-object]').forEach(el=>el.onclick=()=>selectObject(el.dataset.object));
  $('#challenge-subject').innerHTML=options([['ducks','Each duck'],...scene.props.map(p=>[p.id,p.name])],scene.challenge.subject);$('#duration').value=scene.challenge.duration;$('#goal-x').value=scene.challenge.goal[0];$('#goal-y').value=scene.challenge.goal[1];
}
const options=(values,value)=>values.map(([id,text])=>`<option value="${id}" ${value===id?'selected':''}>${text}</option>`).join('');
const numeric=(key,text,value,step='.01')=>`<label>${text}<input data-number="${key}" type="number" value="${value}" step="${step}"></label>`;
function renderInspector(){
  const o=current();if(!o)return;const duck=scene.ducks.includes(o);$('#selection-title').textContent=o.name??o.kind;$('#remove').disabled=duck&&scene.ducks.length===1;$('#duck-inspector').hidden=!duck;
  let html='';
  if(duck){html=`<label>Controller<select id="controller">${options([['target','Follow target'],['flock','Follow companions'],['brain','Fly brain pulses'],['reactive','Reactive comparison'],['manual','Manual'],['light','Light seeking'],['odor','Odor seeking']],o.mode)}</select></label><label>Vision source<select id="source">${options([['eyes','Duck-eye camera'],['webcam','Mac / device webcam']],o.source)}</select></label>${o.source==='webcam'?'<p class="hint">Show a magenta object to follow. Expanding image motion can trigger loom. Frames stay on this device.</p>':''}<div class="pair"><label>Eyes<select id="eyes">${options([['both','Both eyes'],['left','Left only'],['right','Right only'],['none','Both covered']],o.eye)}</select></label><label>Silence<select id="silence">${options([['none','None'],['output','All output'],['forward','DNp09 forward'],['left','DNa left'],['right','DNa right'],['loom','LC / LPLC'],['gf','Giant Fiber']],o.silence)}</select></label></div><label class="check"><input id="active-look" type="checkbox" ${o.activeLook?'checked':''}>Active head looking</label><label class="check"><input id="flow-steer" type="checkbox" ${o.flowSteer?'checked':''}>Steer using optical flow</label><label class="check"><input id="feedback" type="checkbox" ${o.feedback?'checked':''}>Motion feedback</label>${o.mode==='manual'?'<div class="pulses"><button data-manual="walk">↑ Walk</button><button data-manual="stop">■ Stop</button><button data-manual="left">↰ Left</button><button data-manual="right">↱ Right</button></div>':''}<details><summary>Starting pose</summary><div class="pair">${numeric('spawn.0','X (m)',o.spawn[0])}${numeric('spawn.1','Y (m)',o.spawn[1])}${numeric('spawn.2','Yaw (rad)',o.spawn[2])}</div><button id="apply-object">Apply and reset</button></details>`;
  }else if(scene.props.includes(o)){
    html=`<label>Name<input id="object-name" value="${escapeHTML(o.name)}" maxlength="80"></label><div class="pair">${o.position.map((v,i)=>numeric('position.'+i,['X (m)','Y (m)','Z (m)'][i],v)).join('')}${numeric('yaw','Yaw (rad)',o.yaw)}</div><details open><summary>Physical shape</summary><div class="pair">${o.size.map((v,i)=>numeric('size.'+i,['Width / diameter','Depth','Height'][i],v)).join('')}${numeric('mass','Mass (kg)',o.mass)}${numeric('friction','Friction',o.friction)}</div><label class="check"><input id="movable" type="checkbox" ${o.movable?'checked':''}>Free physical body</label><label>Color<input id="object-color" type="color" value="${o.color}"></label></details><details><summary>Animated motion (m/s)</summary><p class="hint">For fixed props. Free bodies move through physics.</p><div class="pair">${o.motion.map((v,i)=>numeric('motion.'+i,['X speed','Y speed','Z speed'][i],v)).join('')}</div></details><button id="move-prop">Move in current run</button><button id="apply-object" class="primary">Apply and reset</button>`;
  }else{html=`<p class="hint">${o.kind==='odor'?'A modeled scalar gradient sampled near the head.':'A physical scene light; camera brightness drives the modeled adapter.'}</p><div class="pair">${o.position.map((v,i)=>numeric('position.'+i,['X (m)','Y (m)'][i],v)).join('')}${numeric('strength','Strength',o.strength)}${numeric('radius','Radius (m)',o.radius)}</div><button id="apply-object" class="primary">Apply and reset</button>`;}
  $('#object-editor').innerHTML=html;
  const patch=value=>{scene=validateScene({...scene,ducks:scene.ducks.map(d=>d.id===o.id?{...d,...value}:d)});send('duck',{id:o.id,patch:value});persistScene();renderScene();};
  for(const [selector,key] of [['controller','mode'],['source','source'],['eyes','eye'],['silence','silence']])if($('#'+selector))$('#'+selector).onchange=e=>{patch({[key]:e.target.value});if(selector==='controller'||selector==='source')renderInspector();};
  for(const [selector,key] of [['active-look','activeLook'],['flow-steer','flowSteer'],['feedback','feedback']])if($('#'+selector))$('#'+selector).onchange=e=>patch({[key]:e.target.checked});
  document.querySelectorAll('[data-manual]').forEach(el=>el.onclick=()=>patch({manual:({walk:[.3,0],stop:[0,0],left:[.25,.65],right:[.25,-.65]})[el.dataset.manual]}));
  if($('#move-prop'))$('#move-prop').onclick=()=>{const position=[0,1,2].map(i=>Number(document.querySelector('[data-number="position.'+i+'"]').value)),yaw=Number(document.querySelector('[data-number="yaw"]').value);pendingPropMove={id:o.id,position};send('move-prop',{id:o.id,position,yaw});};
  if($('#apply-object'))$('#apply-object').onclick=()=>{const next=structuredClone(scene),object=[...next.ducks,...next.props,...next.fields].find(x=>x.id===o.id);
    document.querySelectorAll('[data-number]').forEach(el=>{const [key,index]=el.dataset.number.split('.');if(index!==undefined)object[key][+index]=Number(el.value);else object[key]=Number(el.value);});
    if($('#object-name'))object.name=$('#object-name').value;if($('#movable'))object.movable=$('#movable').checked;if($('#object-color'))object.color=$('#object-color').value;sceneChanged(next);
  };
}
function drawEye(){
  const duck=scene.ducks.find(d=>d.id===selected);if(!duck)return;
  const pixels=lastPixels[duck.source==='webcam'?'webcam':duck.id],canvas=$('#eye'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,W,H);
  if(pixels)ctx.putImageData(new ImageData(new Uint8ClampedArray(pixels),W,H),0,0);
  ctx.fillStyle='#08110d';
  if(duck.eye==='none')ctx.fillRect(0,0,W,H);
  else if(duck.eye==='left')ctx.fillRect(W/2,0,W/2,H);
  else if(duck.eye==='right')ctx.fillRect(0,0,W/2,H);
  const v=state?.agents?.[duck.id]?.vision;if(!v)return;
  const object=duck.mode==='flock'?v.neighbor:v.target;if(object.visible){ctx.strokeStyle=duck.mode==='flock'?'#8eefff':'#fff';ctx.lineWidth=1;ctx.strokeRect(...object.bounds);}
  if($('#flow-overlay').checked){ctx.strokeStyle='#d3ff9b';ctx.lineWidth=.7;for(const f of v.flow.vectors){ctx.beginPath();ctx.moveTo(f.x,f.y);ctx.lineTo(f.x+f.dx*2,f.y+f.dy*2);ctx.stroke();}}
}
const captured=document.createElement('canvas');captured.width=W;captured.height=H;
function webcamFrame(){if(!stream||!video||video.readyState<2)return null;const ctx=captured.getContext('2d',{willReadFrequently:true});ctx.drawImage(video,0,0,W,H);return new Uint8Array(ctx.getImageData(0,0,W,H).data);}
function update(data){
  state=data;paused=data.paused;scene=data.scene;arena?.updateLab(data.body);
  if(pendingPropMove&&scene.props.some(p=>p.id===pendingPropMove.id&&p.position.every((v,i)=>v===pendingPropMove.position[i]))){pendingPropMove=null;persistScene();renderInspector();}
  $('#pause').textContent=paused?'▶ Run':'Ⅱ Pause';$('#clock').textContent=data.body.time.toFixed(2)+' s';$('#live').textContent=paused?'Paused':'● Running';$('#branch-label').textContent=`Branch ${data.branch}${data.replaying?' · replay':''}`;
  const s=data.body.ducks.find(d=>d.id===selected)??data.body.ducks[0],a=data.agents[s.id],n=a?.neural;
  $('#metrics').textContent=`${s.speed.toFixed(2)} m/s · ${s.distance.toFixed(2)} m · ${data.body.collisionCount} contacts`;
  $('#inspect-event').textContent=s.fallen?'Duck fell. Reset to stand.':n?.event.includes('stop reflex')?n.event:a?.input?.reason??'Paused at starting state';
  $('#forward').textContent=(n?.forward??0).toFixed(1)+' Hz';$('#yaw').textContent=s.command[1].toFixed(2)+' rad/s';$('#tilt').textContent=s.tilt.toFixed(1)+'°';$('#feet').textContent=s.contacts.map((c,i)=>`${i?'R':'L'} ${c?'●':'○'}`).join('  ');
  const v=a?.vision,flock=scene.ducks.find(d=>d.id===s.id)?.mode==='flock';$('#vision-status').textContent=v?`${flock?(v.neighbor.visible?'Companion marker detected':'No companion marker'):(v.target.visible?'Target detected':'No target')} · loom ${Math.max(v.loomL,v.loomR).toFixed(2)}`:'No camera sample';
  $('#cost').textContent=`${data.body.ducks.length} duck${data.body.ducks.length>1?'s':''} · ${data.body.cost.toFixed(1)} ms physics`;
  $('#status').textContent=stream?'Webcam active · frames stay on this device':paused?'Ready · Space to run':'Running on this device';
  if(n){plot?.draw(n.fired);if(data.tick%2===0){samples.push(n);if(samples.length>150)samples.shift();if($('#trace').offsetWidth)trace($('#trace'),samples);}}
  $('#rewind').max=Math.max(0,data.history.length-1);$('#rewind').value=data.history.findLastIndex(h=>h.tick<=data.tick);$('#timeline-start').textContent=(data.history[0]?.time??0).toFixed(1)+' s';$('#timeline-end').textContent=(data.history.at(-1)?.time??0).toFixed(1)+' s';
  $('#scores').innerHTML=(scene.challenge.subject==='ducks'?scene.ducks:scene.props.filter(p=>p.id===scene.challenge.subject)).map(d=>{const s=data.scores[d.id];return `<p>${escapeHTML(d.name)}: ${s?.reachedAt!=null?'goal at '+s.reachedAt.toFixed(1)+' s':s?'closest '+s.minGoalDistance.toFixed(2)+' m':'waiting'}</p>`;}).join('');
  if(data.event){events.set(data.event.tick,data.event);if(events.size>1000)events.delete(events.keys().next().value);}
  drawEye();window.duckflyTelemetry={ready,paused,time:data.body.time,tick:data.tick,ducks:data.body.ducks.map(d=>({id:d.id,position:d.position,headPose:d.headPose,cameraPose:d.cameraPose,command:d.command,distance:d.distance,fallen:d.fallen})),agents:data.agents,props:data.body.props,scores:data.scores,event:data.event,collisions:data.body.collisions,collisionCount:data.body.collisionCount,history:data.history,branch:data.branch,scene};
}
const events=new Map();
worker.onmessage=({data})=>{
  if(data.type==='loading')$('#loading-detail').textContent=data.message;
  if(data.type==='challenge-finished')notify('Challenge duration reached. Results are retained in the scene panel.');
  if(data.type==='error'){notify(data.message);$('#loading-detail').textContent=data.message;}
  if(data.type==='ready'){ready=true;scene=data.scene;arena.setScene(scene);renderScene();renderInspector();$('#loading').hidden=true;document.querySelectorAll('[data-control]').forEach(el=>el.disabled=false);}
  if(data.type==='scene'){scene=data.scene;arena.setScene(scene);if(!current())selected=scene.ducks[0].id;renderScene();renderInspector();samples=[];lastPixels={};events.clear();}
  if(data.type==='recording-view'){lastPixels=data.frames;events.clear();for(const event of data.events)events.set(event.tick,event);}
  if(data.type==='state'&&room?.role!=='guest'){update(data);if(room?.role==='host'&&!jobBusy&&(data.paused||performance.now()-lastRoomSent>100)){room.sendState(data);lastRoomSent=performance.now();}}
  if(data.type==='vision-request'){
    arena.updateLab(data.body);const frames=arena.captureEyes();const webcam=webcamFrame();if(webcam)frames.webcam=webcam;
    lastPixels=structuredClone(frames);drawEye();worker.postMessage({type:'frames',ticket:data.ticket,frames},Object.values(frames).map(f=>f.buffer));
  }
  if(data.type==='job-progress'){$('#job-progress').textContent=data.label;$('#job-meter').max=data.total;$('#job-meter').value=data.done;}
  if(data.type==='job-result'){jobBusy=false;lastReport=data.report;$('#job-meter').value=$('#job-meter').max;$('#job-progress').textContent=data.report.interpretation;$('#cancel-job').hidden=true;$('#close-job').hidden=false;$('#save-report').hidden=false;$('#job-results').innerHTML=data.report.rows?'<table><thead><tr><th>Controller</th><th>Mean score</th><th>Falls</th></tr></thead><tbody>'+data.report.rows.map(r=>'<tr><td>'+escapeHTML(r.condition)+'</td><td>'+r.meanScore.toFixed(3)+'</td><td>'+r.trials.filter(t=>t.fallen).length+'</td></tr>').join('')+'</tbody></table>':'<p>Held-out improvement: <strong>'+data.report.gate.meanGain.toFixed(3)+'</strong></p><p>Promotion: <strong>'+(data.report.gate.promote?'passed':'not passed')+'</strong></p><pre>'+escapeHTML(JSON.stringify(data.report.weights,null,2))+'</pre>'; }
  if(data.type==='job-error'){jobBusy=false;$('#job-progress').textContent=data.message;$('#cancel-job').hidden=true;$('#close-job').hidden=false;}
  if(data.type==='export')download('duckfly-recording.json',data.recording);
};
worker.onerror=e=>notify(e.message||'Simulation worker failed');
async function load(){try{const [bytes,circuit]=await Promise.all([fetchBytes('/assets/scene.json.gz'),fetch('/assets/Brain/circuit.json').then(r=>r.json())]);arena=new LabArena($('#arena'),JSON.parse(new TextDecoder().decode(bytes)));arena.onPropDragStart=id=>{selectObject(id);if(!paused&&room?.role!=='guest')send('pause',{value:true});};arena.onPropDrop=(id,position)=>{pendingPropMove={id,position};send('move-prop',{id,position,yaw:scene.props.find(p=>p.id===id).yaw});};plot=new BrainPlot($('#brain-plot'),circuit);renderScene();renderInspector();send('init',{base:new URL('/',location.href).href,scene});if(webcamError)notify(webcamError);}catch(e){$('#loading-detail').textContent=e.message;}}
load();
$('#pause').onclick=()=>send('pause',{value:!paused});$('#reset').onclick=()=>send('reset');$('#view').onclick=()=>arena?.home();$('#follow').onclick=()=>{arena.follow=!arena.follow;$('#follow').setAttribute('aria-pressed',String(arena.follow));};
$('#preset').onchange=e=>{if(e.target.value){sceneChanged(defaultScene(e.target.value));selected='duck-1';e.target.value='';}};
$('#scene-name').onchange=e=>sceneChanged({...scene,name:e.target.value});
$('#challenge-apply').onclick=()=>sceneChanged({...scene,challenge:{...scene.challenge,subject:$('#challenge-subject').value,duration:Number($('#duration').value),goal:[Number($('#goal-x').value),Number($('#goal-y').value)]}});
$('#add').onclick=()=>{const kind=$('#add-kind').value,next=structuredClone(scene),id=kind+'-'+Date.now().toString(36);selected=id;
  if(kind==='duck')next.ducks.push({id,name:'Duck '+(scene.ducks.length+1),spawn:[-.3*scene.ducks.length,.2,0],mode:'flock'});
  else if(['odor','light'].includes(kind))next.fields.push({id,kind,position:[.6,.2],strength:1,radius:.5});
  else next.props.push({id,kind,position:[.5,.25,kind==='wall'?.15:.06],size:kind==='wall'?[.06,.35,.3]:[.12,.12,.12],movable:kind==='ball'});
  sceneChanged(next);
};
$('#remove').onclick=()=>sceneChanged({...scene,challenge:{...scene.challenge,subject:scene.challenge.subject===selected?'ducks':scene.challenge.subject},ducks:scene.ducks.filter(d=>d.id!==selected),props:scene.props.filter(d=>d.id!==selected),fields:scene.fields.filter(d=>d.id!==selected)});
$('#save').onclick=()=>download('duckfly-scene.json',validateScene(scene));$('#share').onclick=async()=>{const url=new URL(window.duckflyHost?'https://duckfly.vercel.app/':location.href);url.hash='scene='+encodeScene(scene);try{await navigator.clipboard.writeText(url.href);notify('Scene link copied. It includes the arena and seed.');}catch{if(!window.duckflyHost){history.replaceState(null,'',url);notify('Scene saved in the address bar. Copy its URL to share.');}else notify('Clipboard unavailable. Use Save to share the scene file.');}};
$('#open').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>150*1024*1024)throw Error('File is too large');const value=JSON.parse(await file.text());if(value.format==='duckfly-recording')send('import',{recording:value});else if(value.format==='duckfly-adapter')send('weights',{id:scene.ducks.some(d=>d.id===selected)?selected:scene.ducks[0].id,weights:value.weights});else sceneChanged(value);}catch(e){notify(e.message);}e.target.value='';};
$('#export').onclick=()=>send('export');$('#branch').onclick=()=>{send('branch');notify('Future inputs will use the current scene. Change a controller or add a stimulus, then run.');};
$('#rewind').onchange=e=>{const checkpoint=state.history[+e.target.value];if(checkpoint)send('rewind',{tick:checkpoint.tick});};
for(const el of document.querySelectorAll('[data-stimulus]'))el.onclick=()=>send('stimulus',{id:scene.ducks.some(d=>d.id===selected)?selected:scene.ducks[0].id,kind:el.dataset.stimulus});
$('#push').onclick=()=>send('push',{id:selected});$('#flow-overlay').onchange=drawEye;
function stopWebcam(){stream?.getTracks().forEach(t=>t.stop());stream=null;if(video)video.srcObject=null;$('#webcam').textContent='Enable webcam';$('#webcam').classList.remove('active-camera');notify('Webcam stopped');}
$('#webcam').onclick=async()=>{if(stream){stopWebcam();return;}try{stream=await navigator.mediaDevices.getUserMedia({video:{width:320,height:240},audio:false});video=document.createElement('video');video.muted=true;video.playsInline=true;video.srcObject=stream;await video.play();$('#webcam').textContent='Stop webcam';$('#webcam').classList.add('active-camera');stream.getVideoTracks()[0].addEventListener('ended',stopWebcam,{once:true});notify('Webcam active. Select “Mac / device webcam” as a duck’s vision source.');}catch(e){stream?.getTracks().forEach(t=>t.stop());stream=null;notify('Camera unavailable: '+e.message);}};
window.addEventListener('pagehide',()=>stream?.getTracks().forEach(t=>t.stop()));
$('#about').onclick=()=>$('#about-dialog').showModal();document.querySelectorAll('[data-close]').forEach(el=>el.onclick=()=>$('#'+el.dataset.close).close());
function showEvent(index){const event=[...events.values()].sort((a,b)=>a.tick-b.tick)[index];if(!event)return;$('#event-time').textContent=`${event.time.toFixed(2)} s · tick ${event.tick} · branch ${event.branch}`;$('#event-content').innerHTML=event.causes.map(c=>`<section><h3>${escapeHTML(scene.ducks.find(d=>d.id===c.id)?.name??c.id)}</h3><p>${escapeHTML(c.input.reason)}</p><table><tbody><tr><td>Vision</td><td>target ${c.vision?.target.visible?'seen':'absent'}, bearing ${(c.vision?.target.bearing??0).toFixed(2)}</td></tr><tr><td>Sensory input</td><td>forward ${c.input.forward.toFixed(3)}, turn ${c.input.turn.toFixed(3)}</td></tr><tr><td>Loom left / right</td><td>${c.input.loomL.toFixed(2)} / ${c.input.loomR.toFixed(2)}</td></tr><tr><td>Neural rates</td><td>DNp09 ${c.neural.forward.toFixed(1)} Hz, DNa ${c.neural.left.toFixed(1)} / ${c.neural.right.toFixed(1)} Hz</td></tr><tr><td>Body command</td><td>${c.command.vx.toFixed(2)} m/s, ${c.command.yaw.toFixed(2)} rad/s</td></tr></tbody></table></section>`).join('');}
$('#inspect-event').onclick=()=>{$('#event-index').max=Math.max(0,events.size-1);$('#event-index').value=events.size-1;showEvent(events.size-1);$('#event-dialog').showModal();};$('#event-index').oninput=e=>showEvent(+e.target.value);
document.addEventListener('keydown',e=>{if(!ready||document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();$('#pause').click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready&&!paused&&room?.role!=='host'&&!jobBusy)send('pause',{value:true});});

function beginJob(type){jobBusy=true;const duck=scene.ducks.find(d=>d.id===selected)??scene.ducks[0];$('#job-title').textContent=type==='learn'?'Learn sensory adapter':'Matched controller comparison';$('#job-progress').textContent='Preparing isolated trials';$('#job-results').innerHTML='';$('#job-meter').value=0;$('#cancel-job').hidden=false;$('#close-job').hidden=true;$('#save-report').hidden=true;$('#job-dialog').showModal();send(type,{id:duck.id,intervention:duck.silence==='none'?'gf':duck.silence});}
$('#compare').onclick=()=>beginJob('compare');$('#learn').onclick=()=>beginJob('learn');$('#cancel-job').onclick=()=>{send('cancel-job');$('#job-progress').textContent='Stopping after the current camera frame';};$('#close-job').onclick=()=>$('#job-dialog').close();$('#save-report').onclick=()=>download(lastReport.format+'.json',lastReport);

room=new ExperimentRoom({
  onStatus:info=>{
    $('#room-status').textContent=info.message;$('#room-button').textContent=info.role==='local'?'Collaborate':`Room · ${info.role}`;
    for(const id of ['pause','reset','compare','learn','export','branch','rewind'])$('#'+id).disabled=info.role==='guest'||!ready;
    window.duckflyRoomTelemetry={role:info.role,state:info.state};
    if(info.role==='guest')worker.postMessage({type:'pause',value:true});
    if(info.state==='connected'&&info.role==='host'&&state)room.sendState(state);
  },
  onCommand:command=>{
    if(jobBusy||!command||!remoteActions.has(command.type))return;
    if(command.type==='stimulus'&&!['walk','left','right','loom'].includes(command.kind))return;
    worker.postMessage(command);
  },
  onState:data=>{
    if(!data?.body||!Array.isArray(data.body.ducks)||data.body.ducks.length>8)throw Error('Invalid shared state');
    const next=validateScene(data.scene);
    for(const d of data.body.ducks)if(!Array.isArray(d.poses)||d.poses.length!==70||d.poses.some(p=>p.length!==7||!p.every(Number.isFinite)))throw Error('Invalid shared body pose');
    const key=JSON.stringify(next);if(key!==remoteSceneKey){scene=next;remoteSceneKey=key;arena.setScene(scene);if(!current())selected=scene.ducks[0].id;renderScene();renderInspector();}
    update(data);lastPixels=arena.captureEyes();drawEye();$('#status').textContent='Shared world · simulation runs on the host';
    window.duckflyRoomTelemetry={role:'guest',state:'connected',sequence:room.lastSequence};
  }
});
function iceServers(){const url=$('#turn-url').value.trim();if(url&&!/^turns?:[^\s]+$/.test(url))throw Error('Use a turn: or turns: server URL');return [{urls:'stun:stun.l.google.com:19302'},...(url?[{urls:url,username:$('#turn-user').value,credential:$('#turn-password').value}]:[])];}
$('#room-button').onclick=()=>$('#room-dialog').showModal();
$('#room-host').onclick=async()=>{try{$('#room-output').value='';$('#room-status').textContent='Gathering connection candidates…';$('#room-output').value=await room.invite(iceServers());$('#room-status').textContent='Send this invitation. Paste the collaborator reply here, then accept it.';}catch(e){notify(e.message);}};
$('#room-join').onclick=async()=>{try{$('#room-output').value='';$('#room-status').textContent='Preparing a reply…';$('#room-output').value=await room.join($('#room-input').value,iceServers());$('#room-status').textContent='Return this reply to the host. Keep this window open until connected.';}catch(e){notify(e.message);}};
$('#room-accept').onclick=async()=>{try{await room.accept($('#room-input').value);$('#room-status').textContent='Connecting to collaborator…';}catch(e){notify(e.message);}};
$('#room-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#room-output').value);notify('Pairing code copied');}catch{$('#room-output').select();notify('Select and copy the pairing code.');}};
$('#room-leave').onclick=()=>{room.disconnect();remoteSceneKey=null;worker.postMessage({type:'scene',scene});$('#room-output').value='';$('#room-input').value='';};
